language: java
jdk:
- oraclejdk8
before_install:
- cd Web
- chmod +x gradlew
- openssl aes-256-cbc -K $encrypted_0a07912baa09_key -iv $encrypted_0a07912baa09_iv -in awskey.pem.enc -out awskey.pem -d

after_success:
- chmod 0400 awskey.pem
- ssh -oStrictHostKeyChecking=no -i awskey.pem ec2-user@52.70.113.152 -t "sudo pkill
  -f java"
- ssh -oStrictHostKeyChecking=no -i awskey.pem ec2-user@52.70.113.152 -t "mysql -u
  root -proot -e 'DROP DATABASE IF EXISTS pintdb; CREATE DATABASE pintdb;'"
- ssh -oStrictHostKeyChecking=no -i awskey.pem ec2-user@52.70.113.152 -t "cd ~/pint
  && sudo ./gradlew build"
- ssh -oStrictHostKeyChecking=no -i awskey.pem ec2-user@52.70.113.152 -f "cd ~/pint
  && sudo ./startapp"

