language: java
jdk:
- oraclejdk8
before_install:
- cd Web
- openssl aes-256-cbc -K $encrypted_2a738054bc80_key -iv $encrypted_2a738054bc80_iv
  -in awskey.pem.enc -out awskey.pem -d
- chmod +x gradlew

after_success:
- chmod 0400 awskey.pem
- ssh -oStrictHostKeyChecking=no -i awskey.pem $user@$instance -t "sudo pkill
  -f java"
- ssh -oStrictHostKeyChecking=no -i awskey.pem $user@$instance -t "mysql -u
  root -proot -e 'DROP DATABASE IF EXISTS pintdb; CREATE DATABASE pintdb;'"
- ssh -oStrictHostKeyChecking=no -i awskey.pem $user@$instance -t "cd ~/pint
  && sudo ./gradlew build"
- ssh -oStrictHostKeyChecking=no -i awskey.pem $user@$instance -f "cd ~/pint
  && sudo ./startapp"
